### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by mvila** [arnthor3/react-delay-render#3]
Something is wrong in the build, in `lib/index.js` I can see:

```js
var _index = require('/Users/arnthor/Development/github/react-delay-render/node_modules/redbox-react/lib/index.js');
```

**Comment by macrozone** [comment]
yeah, saw this as well in a react-native project

**Comment by arnthor3** [comment]
Sorry guys been knee deep in work last couple of weeks. I will take care of this before the weekend. FYI, you could try out react-delay, this is basically just a HOC version of that..

**Comment by macrozone** [comment]
@arnthor3 yeah, just saw that ;-) altough i would prefer hoc versions :-)

thx for your effort
